#!/usr/bin/env bash
#This script pings its ip address argument 5 times

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS=$1

ping -c5 "$IP_ADDRESS"
