#!/usr/bin/env bash
# Configure Nginx server to listen on port 80

# remove the default config file
rm /etc/nginx/sites-enabled/default
# configure Nginx to listen on port 80 
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
